import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/layout/nav/Navbar";
import { Toaster } from "sonner";
import Providers from "@/components/providers/Providers";
import NavigationLoader from "@/components/layout/NavigationLoader";
import Footer from "@/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} dark bg-background`}
      >
        <Providers>
          <NavigationLoader>
            <NavBar />
            <>{children}</>
            <Toaster
              position="bottom-center"
              toastOptions={{
                style: {
                  background: "#333",
                  color: "#fff",
                },
                duration: 5000,
              }}
              richColors
            />
          </NavigationLoader>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
